### ISSUE TITLE
一个小问题请教作者zhuzhuxia1994

### ISSUE THREAD

**Issue by yuanli2333** [zhuzhuxia1994/CK-TensorFlow#1]
作者，你好，感谢分享！！
你使用了光流图片，请问你是如何从RGB图的到光流图的？
因为一般都是从视频中的连续帧获取光流图片，那么你这个项目直接从RGB图片提取了光流图，能否解释一下！

非常感谢！

**Comment by zsano1** [comment]
我也想知道，但是作者说是要自己加上去。所以说是怎么加的呢？有点懵

**Comment by YanGuangyou** [comment]
> 作者，你好，感谢分享！！
> 你使用了光流图片，请问你是如何从RGB图的到光流图的？
> 因为一般都是从视频中的连续帧获取光流图片，那么你这个项目直接从RGB图片提取了光流图，能否解释一下！
> 
> 非常感谢！

请问 您知道是为什么了吗 我也有这个疑问 为什么作者根据原始图片就得到了光流图片？
